export const recommendations = [
  {
    title: "Motivos para contribuir",
    content: "O que ganho contribuindo?",
  },
  {
    title: "Como contribuir",
    content: "Como bombar nas redes?",
  },
  { title: "Requisitos", content: "Preciso de diploma pra ajudar?" },
  { title: "Quero ser herói!", content: "Como ser herói da BCT?" },
  {
    title: "Quero ficar ficar rico!",
    content: "O whitepaper explica como ficar rico?",
  },
  {
    title: "Utilidade do ChatBCT",
    content: "O ChatBCT é útil pra algo?",
  },
  {
    title: "Links +18",
    content: "Onde acho os links proibidos da BCT?",
  },
  {
    title: "Quero ser general!",
    content: "Como virar general dos RAIDS?",
  },
  {
    title: "Sou garoto de programa, como contribuir?",
    content: "Quero contribuir para o GitHub, como faço?",
  },
  {
    title: "Mim dê papai!",
    content: "Onde vejo memes da galera?",
  },
  {
    title: "Community Performance",
    content: "Como monitorar o desempenho da comunidade?",
  },
  {
    title: "Quero BCT no PIX!",
    content: "Como comprar BCT com Pix?",
  },
  {
    title: "BCT vs BTC",
    content: "BCT vs Bitcoin: qual é mais quente?",
  },
  {
    title: "Anedotas Já!",
    content: "Me conta uma piada!",
  },
  {
    title: "Mmemecoins?",
    content: "O que são as memecoins?",
  },
  {
    title: "É golpe?",
    content: "Como evitar golpes ao comprar BCT?",
  },
  {
    title: "Contrato Oficial",
    content: "Qual o contrato da BCT?",
  },
  {
    title: "Rug Check",
    content: "Qual o status do rugcheck da BCT?",
  },
  {
    title: "LP Locked?",
    content: "O que significa LP Locked?",
  },
  {
    title: "Supply da BCT",
    content: "Qual o supply atual da BCT?",
  },
  {
    title: "Parceria OnlyFans?",
    content: "BCT vai ter parceria com OnlyFans?",
  },
  {
    title: "Listagem em Exchanges",
    content: "Por que a BCT não está na Binance?",
  },
  {
    title: "Social da BCT",
    content: "Qual o Twitter oficial da BCT?",
  },
  {
    title: "Futuro da BCT",
    content: "Qual o futuro da BCT?",
  },
  {
    title: "Comparação Quente",
    content: "BCT ou Bitcoin: qual esquenta mais?",
  },
  {
    title: "Tutorial Phantom",
    content: "Como comprar BCT usando a Phantom Wallet?",
  },
  {
    title: "Tutorial OKX",
    content: "Como comprar BCT usando a OKX Wallet?",
  },
  {
    title: "Raids Épicas",
    content: "Como participar dos RAIDS da BCT?",
  },
  {
    title: "Prêmio do Zoeiro",
    content: "Qual o prêmio pro maior zoeiro da comunidade?",
  },
  {
    title: "Martina Oliveira",
    content: "Por que a Martina lançou a BCT?",
  },
  {
    title: "Dados Técnicos",
    content: "Onde leio a proposta técnica da BCT?",
  },
  {
    title: "Mint Address",
    content: "Qual o endereço de mint da BCT?",
  },
  {
    title: "Hype ou Real?",
    content: "BCT é só hype ou tem função?",
  },
  {
    title: "Trocadilhos BCT",
    content: "Faz um trocadilho com BCT!",
  },
  {
    title: "Meta Secreta",
    content: "Qual o segredo da meta de $0.34?",
  },
  { title: "Preço da BCT", content: "Qual o preço atual da BCT?" },
  { title: "Holders da BCT", content: "Quantos holders a BCT tem?" },
  { title: "Market Cap da BCT", content: "Qual o market cap da BCT?" },
  { title: "BCT na Solana", content: "Por que a BCT está na Solana?" },
  { title: "BCT vs Shiba Inu", content: "BCT é melhor que Shiba Inu?" },
  { title: "BCT Queimadas", content: "A BCT tem token burn?" },
  { title: "Staking de BCT", content: "Posso fazer staking de BCT?" },
  { title: "NFTs da BCT", content: "BCT vai lançar NFTs?" },
  { title: "BCT no Metaverso", content: "BCT terá presença no metaverso?" },
  { title: "BCT Merch", content: "Há merchandise oficial da BCT?" },
  { title: "Auditoria da BCT", content: "A BCT passou por auditoria?" },
  { title: "LP da BCT", content: "Qual a porcentagem de BCT no pool?" },
  { title: "Rug Pull", content: "Como evitar rug pulls em memecoins?" },
  { title: "Contrato BCT/SOL", content: "Qual o contrato do par BCT/SOL?" },
  { title: "Mutabilidade da BCT", content: "A BCT é um token mutável?" },
  { title: "Update Authority", content: "Quem é a update authority da BCT?" },
  { title: "Mint da BCT", content: "Onde a BCT foi cunhada?" },
  {
    title: "Verificar BCT",
    content: "Como verificar se comprei a BCT verdadeira?",
  },
  { title: "Phishing", content: "Como evitar golpes de phishing com BCT?" },
  { title: "Recuperar BCT", content: "Como recuperar BCT perdidas?" },

  { title: "Velocidade da Solana", content: "Por que a Solana é tão rápida?" },
  {
    title: "Taxas da Solana",
    content: "Quanto custa uma transação na Solana?",
  },
  { title: "Solana vs Cardano", content: "Solana é melhor que Cardano?" },
  { title: "Projetos na Solana", content: "Quais projetos usam Solana?" },
  { title: "Provas de História", content: "O que é Proof of History?" },
  { title: "Solana Wallets", content: "Qual carteira usar na Solana?" },
  { title: "Solana Outages", content: "A Solana já teve quedas?" },
  { title: "Validadores Solana", content: "Como ser validador da Solana?" },
  { title: "DeFi na Solana", content: "O que é Raydium?" },
  { title: "NFTs na Solana", content: "Como comprar NFTs na Solana?" },
  { title: "Listar BCT", content: "Como listar BCT em uma exchange?" },
  { title: "KYC na OKX", content: "A OKX exige KYC?" },
  { title: "Phantom vs Metamask", content: "Phantom é melhor que Metamask?" },
  { title: "Taxas da Raydium", content: "Quanto custa swap na Raydium?" },
  { title: "Liquidez na Raydium", content: "Como adicionar liquidez à BCT?" },
  { title: "Multi-Chain Wallets", content: "A OKX suporta Solana?" },
  { title: "Hardware Wallets", content: "Posso guardar BCT em Ledger?" },
  { title: "Recuperar Carteira", content: "Como recuperar a Phantom Wallet?" },
  { title: "Seed Phrase", content: "O que fazer se perder minha seed phrase?" },
  { title: "Tokenomics", content: "Onde vejo a tokenomics da BCT?" },
  { title: "Twitter da BCT", content: "Qual o Twitter da comunidade BCT?" },
  { title: "Discord da BCT", content: "Onde está o Discord da BCT?" },
  {
    title: "Trading Competitions",
    content: "Há competições de trading com BCT?",
  },
  { title: "Memes Virais", content: "Qual meme da BCT bombou mais?" },
  { title: "Influencers da BCT", content: "Quem apoia a BCT?" },
  { title: "Bounty Programs", content: "Há programas de recompensa na BCT?" },
  { title: "Governança", content: "A BCT tem DAO?" },
  { title: "Eventos ao Vivo", content: "Quando é a próxima live da Martina?" },
  { title: "Parcerias Secretas", content: "BCT tem parcerias não anunciadas?" },
  { title: "Doações", content: "BCT apoia alguma causa social?" },
  { title: "Idade da Martina", content: "Qual a idade da Martina Oliveira?" },
  { title: "Signo da Martina", content: "Qual o signo da Martina Oliveira?" },
  { title: "Fama da Martina", content: "Por que Martina é famosa?" },
  { title: "OnlyFans da Martina", content: "Martina tem OnlyFans?" },
  { title: "Tatuagem da BCT", content: "Onde Martina tatuou a BCT?" },
  { title: "Vida Pessoal", content: "O que Martina faz no tempo livre?" },
  { title: "Projetos Futuros", content: "Quais são os planos da Martina?" },
  { title: "Beiçola da Privacy", content: "Quem é a Beiçola da Privacy?" },
  { title: "Conteúdo +18", content: "BCT dá acesso a conteúdo adulto?" },
  { title: "Reality Show", content: "Quando sai o reality da BCT?" },
  { title: "Trocadilhos", content: "Faz um trocadilho com BCT!" },
  { title: "Piadas Cripto", content: "Conta uma piada sobre Bitcoin!" },
  { title: "Challenges", content: "Há desafios de meme da BCT?" },
  { title: "Hino da BCT", content: "Existe um hino oficial da BCT?" },
  { title: "Celebridades", content: "Qual famoso já mencionou a BCT?" },
  { title: "Teorias da Conspiração", content: "BCT está ligada ao Elon Musk?" },
  { title: "Vídeos Engraçados", content: "Onde acho vídeos da comunidade?" },
  { title: "Meme Contests", content: "Como participar de concursos de memes?" },
  { title: "Zoeira Infinita", content: "Qual a zoeira mais famosa da BCT?" },
  { title: "Hype Train", content: "Quando começa o próximo pump da BCT?" },
  { title: "Casos de Uso", content: "Onde posso gastar BCT?" },
  { title: "BCT no Varejo", content: "Lojas aceitam BCT?" },
  { title: "Integração DeFi", content: "BCT terá farming?" },
  { title: "BCT na Gamificação", content: "Há jogos usando BCT?" },
  { title: "Educação", content: "BCT oferece cursos sobre cripto?" },
  { title: "Roadmap", content: "Onde vejo o roadmap da BCT?" },
  { title: "Meta $1", content: "O que acontece se a BCT chegar a $1?" },
  { title: "Meta $0.10", content: "Qual o plano para BCT atingir $0.10?" },
  { title: "Queima de Tokens", content: "Haverá queima de BCT?" },
  { title: "Inflação", content: "A BCT é inflacionária?" },
];
